-- GCStudio · Seed de cursos (generado desde src/content/courses.ts)
-- Derivado del material real. NO editar a mano: regenerar con node scripts/generate-seed.mjs

begin;

-- ===== Laminado de Cejas =====
insert into courses (id, slug, title, subtitle, description, level, status, video_duration_seconds, video_asset_id, cover_image, price_ars, position)
values ('course-laminado', 'laminado-de-cejas', 'Laminado de Cejas', 'Full Brows · Taller Cejas Perfectas', 'Formación profesional en diseño, perfilado, henna y laminado de cejas. Para profesionales y principiantes. Dictado por Geraldine Colman.', 'Profesionales y principiantes', 'published', 529.92, null, '/media/covers/laminado.jpg', null, 0)
on conflict (id) do update set
  slug = excluded.slug, title = excluded.title, subtitle = excluded.subtitle,
  description = excluded.description, level = excluded.level,
  video_duration_seconds = excluded.video_duration_seconds, cover_image = excluded.cover_image,
  position = excluded.position;
insert into modules (id, course_id, position, title, summary)
values ('mod-lam-01', 'course-laminado', 1, 'Fundamentos y diseño', 'La ceja como marco del rostro, materiales y visagismo.')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0101', 'mod-lam-01', 'course-laminado', 'que-son-las-cejas', 1, '¿Qué son las cejas y por qué importan?', 'La ceja como marco del rostro y por qué un diseño correcto realza y armoniza las facciones.', 'pdf', '[{"kind":"paragraph","text":"Las cejas son el marco de nuestro rostro. Un diseño correcto puede realzar y armonizar las facciones, u ocasionar el resultado opuesto si se ejecuta de mala manera."},{"kind":"callout","tone":"gold","title":"Principio rector","text":"A lo largo de los años cambiaron las modas de grosor, longitud y color, pero el resultado siempre debe ser un diseño natural, apto y personalizado para el rostro, en base a medidas exactas."}]'::jsonb, '["Entender el rol de la ceja en la armonía facial","Comprender por qué el diseño debe ser natural y personalizado"]'::jsonb, '["La ceja es el marco del rostro","Un diseño correcto realza; uno mal ejecutado logra el efecto opuesto","Las modas cambian (grosor, longitud, color) pero el resultado siempre debe ser natural"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lesson_resources (id, lesson_id, title, type, url, body, position)
values ('res-lam-0101-pdf', 'les-lam-0101', 'PDF del curso — Laminado de Cejas', 'pdf', '/media/resources/laminado.pdf', null, 0)
on conflict (id) do update set title = excluded.title, url = excluded.url, body = excluded.body;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0102', 'mod-lam-01', 'course-laminado', 'materiales-laminado', 2, 'Materiales de trabajo', 'El kit completo para diseñar y perfilar cejas de forma profesional.', 'pdf', '[{"kind":"list","title":"Materiales necesarios","items":["Pinza de depilar recta, diagonal o en punta","Calibre medidor","Lápiz dermográfico y lapicera de gel blanca","Tijera de punta fina","Perfilador o navaja profesional","Hilo de algodón, brow shampoo, algodón y cepillos"]}]'::jsonb, '["Conocer cada material y su función","Armar tu kit de trabajo"]'::jsonb, '["Herramientas de medición y marcación","Herramientas de depilación","Consumibles e higiene"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lesson_resources (id, lesson_id, title, type, url, body, position)
values ('res-lam-0102-check', 'les-lam-0102', 'Checklist de materiales', 'checklist', null, '[{"kind":"list","title":"Antes de empezar, verificá tener","items":["Pinza (recta / diagonal / punta)","Calibre medidor","Lápiz dermográfico + lapicera de gel blanca","Tijera de punta fina","Perfilador o navaja profesional","Hilo de algodón + brow shampoo + algodón + cepillos"]}]'::jsonb, 0)
on conflict (id) do update set title = excluded.title, url = excluded.url, body = excluded.body;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0103', 'mod-lam-01', 'course-laminado', 'visagismo-medicion-hilo', 3, 'Visagismo: medición con hilo', 'Técnica para determinar anchura, grosor, dimensión y curvatura según el rostro.', 'both', '[{"kind":"paragraph","text":"El visagismo de cejas es una técnica para saber qué diseño (anchura, grosor, dimensión y curvatura) deben tener las cejas según los rasgos y dimensiones del rostro. Bien hecho, aporta equilibrio y armonía, haciendo lucir el rostro más simétrico."}]'::jsonb, '["Aplicar visagismo para equilibrar el rostro","Medir con hilo para lograr simetría"]'::jsonb, '["Anchura, grosor, dimensión y curvatura","Aporta equilibrio y armonía","Rostro más simétrico"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lesson_resources (id, lesson_id, title, type, url, body, position)
values ('res-lam-0103-pdf', 'les-lam-0103', 'PDF del curso — Laminado de Cejas', 'pdf', '/media/resources/laminado.pdf', null, 0)
on conflict (id) do update set title = excluded.title, url = excluded.url, body = excluded.body;
insert into modules (id, course_id, position, title, summary)
values ('mod-lam-02', 'course-laminado', 2, 'Perfilado y depilación', 'Los tres servicios, el método de depilación y el paso a paso.')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0201', 'mod-lam-02', 'course-laminado', 'tres-servicios', 1, 'Los 3 servicios a ofrecer', 'Perfilado clásico, perfilado con henna y Full Brows (laminado).', 'pdf', '[{"kind":"table","title":"Comparativa de servicios","headers":["Servicio","En qué consiste"],"rows":[["1 · Perfilado clásico","Visagismo y marcación correspondiente. Luego se depila con pinza y navaja."],["2 · Perfilado con henna","Perfilado clásico y, una vez terminado, se rellena el diseño de visagismo con henna."],["3 · Full Brows (laminado)","Primero el laminado, luego el visagismo, la depilación y por último la henna (opcional)."]]}]'::jsonb, '["Diferenciar los tres servicios","Saber qué incluye cada uno"]'::jsonb, '["Perfilado clásico","Perfilado con henna","Full Brows (laminado)"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0202', 'mod-lam-02', 'course-laminado', 'metodo-depilacion', 2, 'Método de depilación (pinza y navaja)', 'Cómo retirar el exceso con pinza y las pelusas al ras con la navaja.', 'both', '[{"kind":"paragraph","text":"Una vez realizado el diseño y marcado con el lápiz blanco, retiramos con la pinza todo el exceso de vello por fuera del mismo. Con la navaja, muy cuidadosamente, retiramos solo las pelusas al ras del diseño (no vello) para que el trabajo quede mucho más limpio."}]'::jsonb, '["Depilar por fuera del diseño con pinza","Retirar pelusas al ras con navaja"]'::jsonb, '["Marcar con lápiz blanco antes de depilar","Pinza: exceso por fuera del diseño","Navaja: solo pelusas al ras, no vello"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0203', 'mod-lam-02', 'course-laminado', 'paso-a-paso-perfilado', 3, 'Paso a paso del perfilado', 'El procedimiento completo, de la limpieza a la corrección final.', 'both', '[{"kind":"steps","title":"Procedimiento","items":["Limpiar muy bien la zona de las cejas con lash shampoo y retirar con un algodón humedecido.","Realizar la marcación con hilo y dibujar el diseño con la lapicera de gel blanca. Es importante mostrar el diseño a la clienta antes de comenzar.","Una vez aprobado el diseño, retirar todo el exceso de vello por fuera de la marcación blanca y, con la navaja, cuidadosamente retirar la pelusa.","Borrar toda la marcación con algodón y antibacterial o agua. Si es necesario, corregir."]}]'::jsonb, '["Ejecutar el perfilado en orden","Validar el diseño con la clienta"]'::jsonb, '["Limpieza","Marcación con hilo","Aprobación del diseño","Depilación y corrección"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lesson_resources (id, lesson_id, title, type, url, body, position)
values ('res-lam-0203-guide', 'les-lam-0203', 'Guía de procedimiento del perfilado', 'guide', null, '[{"kind":"steps","items":["Limpieza con lash shampoo","Marcación con hilo + diseño con gel blanca","Mostrar y aprobar el diseño","Depilar exceso (pinza) + pelusas al ras (navaja)","Borrar marcación y corregir"]}]'::jsonb, 0)
on conflict (id) do update set title = excluded.title, url = excluded.url, body = excluded.body;
insert into modules (id, course_id, position, title, summary)
values ('mod-lam-03', 'course-laminado', 3, 'Henna', 'Qué es la henna, cómo se aplica y cómo se mezclan los tonos.')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0301', 'mod-lam-03', 'course-laminado', 'henna-que-es', 1, 'Qué es la henna y cuánto dura', 'Materiales de henna y su duración en pelo y piel.', 'pdf', '[{"kind":"list","title":"Materiales","items":["Henna marrón y negra (se pueden mezclar entre sí)","Activador","Pincel biselado","Hisopos / micro hisopos / algodón"]},{"kind":"paragraph","text":"La duración depende de la frecuencia de lavado y del skincare de la clienta. Aproximadamente el color permanece en el PELO al menos 10 días y en la PIEL de 5 a 10 días."}]'::jsonb, '["Conocer los materiales de henna","Explicar la duración a la clienta"]'::jsonb, '["Materiales","Duración en pelo (~10 días)","Duración en piel (5–10 días)"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0302', 'mod-lam-03', 'course-laminado', 'henna-aplicacion-tonos', 2, 'Aplicación y mezcla de tonos', 'Preparación, tiempos de acción y cómo lograr cada tono de castaño.', 'pdf', '[{"kind":"steps","title":"Cómo utilizar la henna","items":["Preparar en un vaso dappen una parte de henna y otra de activador (partes iguales).","Mezclar muy bien hasta obtener una mezcla homogénea.","Aplicar inmediatamente sobre la piel con el pincel.","Dejar actuar de 5 a 15 minutos (retirando el inicio antes) con algodón y agua."]},{"kind":"table","title":"Cómo mezclamos los tonos","headers":["Mezcla","Resultado"],"rows":[["Rubio y negro en partes iguales","Castaño medio"],["Más rubio y un poco de negro","Castaño claro"],["Más negro y un poco de rubio","Castaño oscuro"]]}]'::jsonb, '["Preparar y aplicar la henna","Mezclar tonos según el resultado buscado"]'::jsonb, '["Partes iguales henna + activador","5 a 15 minutos de acción","Mezcla de tonos"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into modules (id, course_id, position, title, summary)
values ('mod-lam-04', 'course-laminado', 4, 'Laminado (Full Brows)', 'Qué es el laminado y su paso a paso completo.')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0401', 'mod-lam-04', 'course-laminado', 'laminado-que-es', 1, 'Qué es el laminado de cejas', 'Tratamiento semipermanente para dar forma, grosor y realzar el color.', 'pdf', '[{"kind":"paragraph","text":"El laminado de cejas es un tratamiento semipermanente con el que podemos dar forma a los vellos curvos o rebeldes que con un perfilado clásico no podríamos corregir. También se utiliza en cejas finas para generar grosor y dar una forma adecuada. Cabe destacar que realza el color natural del vello, haciéndolo ver más poblado y llamativo."}]'::jsonb, '["Explicar el laminado y sus beneficios","Detectar cuándo indicarlo"]'::jsonb, '["Da forma a vellos rebeldes que el perfilado no corrige","Genera grosor en cejas finas","Realza el color natural del vello"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0402', 'mod-lam-04', 'course-laminado', 'laminado-paso-a-paso', 2, 'Paso a paso del laminado', 'Permanente, neutralizante y botox: tiempos y técnica.', 'both', '[{"kind":"steps","title":"Procedimiento","items":["Limpiar muy bien la zona de las cejas con lash shampoo y retirar con algodón humedecido.","Aplicar el paso N°1 (permanente) en toda la ceja, tratando de no tocar la piel, y dejar actuar de 10 a 15 minutos según el tipo de vello.","Retirar el paso N°1 con algodón seco y colocar el paso N°2 (neutralizante); dejar actuar el mismo tiempo que el anterior.","Retirar el paso N°2 con algodón humedecido, aplicar botox (indispensable), dejar actuar 10 minutos y retirar."]},{"kind":"callout","tone":"warning","title":"Tiempos según el vello","text":"Los tiempos de acción se ajustan al tipo de vello. El botox final es indispensable para nutrir y sellar el resultado."}]'::jsonb, '["Aplicar los pasos 1 y 2 con los tiempos correctos","Finalizar con botox"]'::jsonb, '["Paso 1 permanente","Paso 2 neutralizante","Botox indispensable"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into modules (id, course_id, position, title, summary)
values ('mod-lam-05', 'course-laminado', 5, 'Cuidados, higiene y seguridad', 'Cuidados post servicio, bioseguridad y normativa ANMAT.')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0501', 'mod-lam-05', 'course-laminado', 'cuidados-post-servicio', 1, 'Cuidados post servicio', 'Qué indicar a la clienta en las primeras 24 horas y después.', 'pdf', '[{"kind":"list","title":"Primeras 24 hs","items":["No lavar ni refregar la zona para evitar remover el producto de la piel o el vello.","No aplicar maquillaje ni ningún producto cosmético."]},{"kind":"list","title":"Luego de las 24 hs","items":["Evitar refregar la zona y evitar el agua caliente.","No utilizar productos cosméticos ni desmaquillantes en la zona."]}]'::jsonb, '["Entregar indicaciones claras de cuidado","Proteger el resultado"]'::jsonb, '["Primeras 24 h","Luego de 24 h"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lesson_resources (id, lesson_id, title, type, url, body, position)
values ('res-lam-0501-ficha', 'les-lam-0501', 'Ficha de cuidados para la clienta', 'guide', null, '[{"kind":"list","title":"Primeras 24 hs","items":["No lavar ni refregar","Sin maquillaje ni cosméticos"]},{"kind":"list","title":"Luego de 24 hs","items":["Sin agua caliente ni refregar","Sin cosméticos ni desmaquillantes"]}]'::jsonb, 0)
on conflict (id) do update set title = excluded.title, url = excluded.url, body = excluded.body;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lam-0502', 'mod-lam-05', 'course-laminado', 'higiene-anmat', 2, 'Higiene, espacio de trabajo y ANMAT', 'Bioseguridad del espacio y verificación de productos aprobados.', 'pdf', '[{"kind":"list","title":"Higiene y espacio de trabajo","items":["Desinfectar siempre manos y materiales.","Los materiales descartables no se pueden volver a usar.","Zona de trabajo limpia y desinfectada.","Procurar el uso de barbijo.","Camilla con colchoneta o silla cómoda.","Ambiente con buen aroma."]},{"kind":"callout","tone":"warning","title":"Importante — ANMAT","text":"Al comprar cualquier producto debemos verificar que esté aprobado por la ANMAT (Administración Nacional de Medicamentos, Alimentos y Tecnología Médica) para garantizar productos eficaces, seguros y de calidad."}]'::jsonb, '["Mantener un espacio seguro y desinfectado","Verificar aprobación ANMAT"]'::jsonb, '["Desinfección","Descartables","ANMAT"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;

-- ===== Lifting de Pestañas =====
insert into courses (id, slug, title, subtitle, description, level, status, video_duration_seconds, video_asset_id, cover_image, price_ars, position)
values ('course-lifting', 'lifting-de-pestanas', 'Lifting de Pestañas', 'Lash Lifting', 'Formación profesional en lifting de pestañas: química, moldes, curvaturas y seguridad. Para profesionales y principiantes. Dictado por Geraldine Colman.', 'Profesionales y principiantes', 'published', 857.31, null, '/media/covers/lifting.jpg', null, 1)
on conflict (id) do update set
  slug = excluded.slug, title = excluded.title, subtitle = excluded.subtitle,
  description = excluded.description, level = excluded.level,
  video_duration_seconds = excluded.video_duration_seconds, cover_image = excluded.cover_image,
  position = excluded.position;
insert into modules (id, course_id, position, title, summary)
values ('mod-lif-01', 'course-lifting', 1, 'Fundamentos del lifting', 'Qué es el lifting, materiales y estructura del pelo.')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0101', 'mod-lif-01', 'course-lifting', 'que-es-el-lifting', 1, 'Qué es el lifting y su diferencia con la permanente', 'Levantar la pestaña desde la raíz y en qué se diferencia de la permanente.', 'pdf', '[{"kind":"paragraph","text":"El lifting de pestañas es un procedimiento estético que implica levantar las pestañas desde la raíz para dar un aspecto de proyección y curvatura. Al realizarlo modificamos la estructura del pelo con químicos y herramientas."},{"kind":"callout","tone":"gold","title":"Diferencia con la permanente","text":"La diferencia en el procedimiento radica únicamente en el molde, ya que ambas técnicas pueden realizarse con el mismo químico."}]'::jsonb, '["Definir el lifting","Diferenciarlo de la permanente"]'::jsonb, '["Levanta la pestaña desde la raíz","Modifica la estructura con químicos y herramientas","La diferencia con la permanente es el molde"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lesson_resources (id, lesson_id, title, type, url, body, position)
values ('res-lif-0101-pdf', 'les-lif-0101', 'PDF del curso — Lifting de Pestañas', 'pdf', '/media/resources/lifting.pdf', null, 0)
on conflict (id) do update set title = excluded.title, url = excluded.url, body = excluded.body;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0102', 'mod-lif-01', 'course-lifting', 'materiales-lifting', 2, 'Materiales', 'El kit completo para realizar lifting de pestañas.', 'pdf', '[{"kind":"list","title":"Materiales necesarios","items":["Lash shampoo","Algodón","Moldes","Pinza o herramienta para lifting y peines para lifting","Pincel o aplicadores","Químicos"]}]'::jsonb, '["Conocer cada material","Armar tu kit de lifting"]'::jsonb, '["Moldes y herramientas","Químicos","Consumibles"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0103', 'mod-lif-01', 'course-lifting', 'el-pelo-componentes', 3, 'El pelo y sus componentes', 'Queratina, melanina, agua y lípidos: qué aporta cada uno.', 'pdf', '[{"kind":"paragraph","text":"El pelo es un filamento formado por una fibra de queratina, constituido por raíz y tallo. Se forma en un folículo piloso de la dermis y contiene agua, melanina, queratina y lípidos."},{"kind":"table","title":"Componentes","headers":["Componente","Función"],"rows":[["Queratina","Proteína fibrosa responsable de la estructura y resistencia del pelo. Aporta fuerza y rigidez."],["Melanina","Pigmento que da color al pelo y la piel. Su cantidad determina el color y aporta flexibilidad."],["Agua y lípidos","El agua da elasticidad; los lípidos mantienen el pelo suave y flexible. Fundamentales para su salud."]]}]'::jsonb, '["Comprender la composición del pelo","Relacionar componentes con el resultado"]'::jsonb, '["Queratina","Melanina","Agua y lípidos"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into modules (id, course_id, position, title, summary)
values ('mod-lif-02', 'course-lifting', 2, 'Química del lifting', 'Acción de los químicos, la corteza y los tiempos de acción.')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0201', 'mod-lif-02', 'course-lifting', 'correcta-accion-quimicos', 1, 'Correcta acción de los químicos (Paso 1 y 2)', 'Qué hace cada paso sobre la cutícula, la queratina y la melanina.', 'pdf', '[{"kind":"steps","title":"Acción química","items":["Paso 1: fragmenta la cutícula y comienza a romper moléculas de queratina (perdemos fuerza en el pelo); luego sigue por la melanina, donde perdemos un poco de color.","Paso 2: se encarga de que el agente del paso 1 se detenga y, con ayuda del oxidante y del Ph, esas cutículas se vuelven a sellar."]}]'::jsonb, '["Entender la acción del paso 1","Entender el sellado del paso 2"]'::jsonb, '["Paso 1: fragmenta la cutícula","Paso 2: detiene y sella"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0202', 'mod-lif-02', 'course-lifting', 'corteza-cortex', 2, 'La corteza (cortex) y el cambio de estructura', 'Por qué abrimos la cutícula para llegar al cortex.', 'pdf', '[{"kind":"paragraph","text":"En un lifting/laminado, el objetivo del paso 1 y 2 es abrir las cutículas para llegar a la corteza (cortex), porque ahí es donde logramos los cambios de estructura. En el proceso perdemos una cantidad muy importante de lípidos, queratina y melanina."}]'::jsonb, '["Ubicar dónde se produce el cambio","Dimensionar la pérdida de componentes"]'::jsonb, '["Abrir cutículas","Llegar al cortex","Pérdida de lípidos, queratina y melanina"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0203', 'mod-lif-02', 'course-lifting', 'tiempos-de-accion', 3, 'Tiempos de acción: rápida, lenta y moderada', 'Cómo identificar los químicos por su tiempo de acción y su Ph.', 'pdf', '[{"kind":"paragraph","text":"Los químicos se identifican por sus tiempos de acción, que varían según su Ph."},{"kind":"table","title":"Tipos de acción","headers":["Acción","Tiempos"],"rows":[["Rápida","Cortos tiempos de acción (7-8-9-10-11-12-13)"],["Lenta","Tiempos largos (14-16-18-20-22)"],["Moderada","Intermedia, ni muy larga ni muy corta (entre 12 y 18)"]]}]'::jsonb, '["Clasificar químicos por tiempo de acción","Relacionar el Ph con la velocidad"]'::jsonb, '["Rápida","Lenta","Moderada"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0204', 'mod-lif-02', 'course-lifting', 'quimicos-por-marca', 4, 'Químicos por marca, botox, keratinas y pegamentos', 'Catálogo de referencia según la acción y el uso.', 'pdf', '[{"kind":"table","title":"Catálogo de químicos (según el material)","headers":["Categoría","Marcas citadas"],"rows":[["Acción lenta","DLUX (paso 1 y 2), Dolly Lash (paso 1 y 2)"],["Acción rápida y moderada","Dermolash, Easy Kit Neicha, Lion Beauty"],["Acción rápida (no recomendados)","Lash Lifting, Iconsign, Meisheng"],["Botox y keratinas","Melania, Puluk Neicha, Lion Beauty"],["Pegamentos y bálsamos","Neicha, Iconsign, Cherimoya"]]}]'::jsonb, '["Reconocer marcas por tipo de acción","Identificar botox, keratinas y pegamentos"]'::jsonb, '["Acción lenta","Rápida/moderada","No recomendados","Botox y keratinas"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into modules (id, course_id, position, title, summary)
values ('mod-lif-03', 'course-lifting', 3, 'Moldes y curvaturas', 'Herramientas, moldes y las curvas C·U·D·LD.')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0301', 'mod-lif-03', 'course-lifting', 'herramientas-moldes', 1, 'Herramientas y moldes', 'El molde como instrumento principal para modificar el pelo.', 'pdf', '[{"kind":"paragraph","text":"Los moldes son el instrumento principal para la modificación del pelo. Lo importante es entenderlos para lograr cambios sin dificultades. Las herramientas base son: moldes, cepillos y herramienta."}]'::jsonb, '["Conocer las herramientas","Entender el rol del molde"]'::jsonb, '["Moldes","Cepillos","Herramienta"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0302', 'mod-lif-03', 'course-lifting', 'curvas-formatos-moldes', 2, 'Curvas (C·U·D·LD) y formatos de moldes', 'Qué curva lograr según el molde, el ojo y la clienta.', 'pdf', '[{"kind":"paragraph","text":"Las diferentes curvas se logran según el molde que utilicemos y la aplicación del químico. Las más utilizadas son C, U, D y LD. La elección depende del ojo, el gusto de la clienta y el consejo profesional."},{"kind":"table","title":"Formatos de moldes","headers":["Formato","Efecto","Punto más alto"],"rows":[["Plano / semiplano","Full up","Abajo (S-M molde nube)"],["Semirredondo / curva U","Efecto muñeca","Por el medio (M1-M2 molde nube)"],["Redondo / curva C","Full curvatura","Arriba (L molde nube)"]]}]'::jsonb, '["Elegir la curva adecuada","Relacionar formato de molde con el efecto"]'::jsonb, '["Curvas C·U·D·LD","Plano / semiplano","Semirredondo / redondo"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into modules (id, course_id, position, title, summary)
values ('mod-lif-04', 'course-lifting', 4, 'Cuidados, seguridad y mala praxis', 'Cuidados post servicio, errores frecuentes y bioseguridad.')
on conflict (id) do update set title = excluded.title, summary = excluded.summary, position = excluded.position;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0401', 'mod-lif-04', 'course-lifting', 'cuidados-post-servicio-lifting', 1, 'Cuidados post servicio', 'Indicaciones para las primeras 12 y 24 horas.', 'pdf', '[{"kind":"list","title":"Primeras 12 hs","items":["No lavar ni refregar la zona para evitar remover el producto del pelo.","No aplicar maquillaje ni mojarlas."]},{"kind":"list","title":"Luego de las 24 hs","items":["Hidratarlas con keratina o serum.","Evitar máscaras a prueba de agua y usar desmaquillantes bifásicos que faciliten la remoción del maquillaje."]}]'::jsonb, '["Entregar indicaciones claras","Cuidar la durabilidad del lifting"]'::jsonb, '["Primeras 12 h","Luego de 24 h","Hidratación"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lesson_resources (id, lesson_id, title, type, url, body, position)
values ('res-lif-0401-ficha', 'les-lif-0401', 'Ficha de cuidados para la clienta', 'guide', null, '[{"kind":"list","title":"Primeras 12 hs","items":["No lavar ni refregar","Sin maquillaje ni mojar"]},{"kind":"list","title":"Luego de 24 hs","items":["Hidratar con keratina/serum","Desmaquillante bifásico"]}]'::jsonb, 0)
on conflict (id) do update set title = excluded.title, url = excluded.url, body = excluded.body;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0402', 'mod-lif-04', 'course-lifting', 'mala-praxis', 2, 'Mala praxis y cómo evitarla', 'Las causas más frecuentes de un mal resultado.', 'pdf', '[{"kind":"list","title":"Causas principales de mala praxis","items":["Colocar químicos en las puntas cuando no es necesario.","Mala elección del molde.","Tiempos de acción incorrectos para el tipo de pelo.","Productos muy alcalinos."]}]'::jsonb, '["Reconocer errores frecuentes","Prevenir la mala praxis"]'::jsonb, '["Químicos en las puntas","Mala elección del molde","Tiempos incorrectos","Productos alcalinos"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;
insert into lesson_resources (id, lesson_id, title, type, url, body, position)
values ('res-lif-0402-check', 'les-lif-0402', 'Checklist de control de calidad', 'checklist', null, '[{"kind":"list","title":"Antes de cerrar el servicio, verificá","items":["No colocaste químico en las puntas sin necesidad","Elegiste el molde correcto para el ojo","Respetaste los tiempos según el tipo de pelo","Evitaste productos demasiado alcalinos"]}]'::jsonb, 0)
on conflict (id) do update set title = excluded.title, url = excluded.url, body = excluded.body;
insert into lessons (id, module_id, course_id, slug, position, title, summary, source, content, objectives, highlights, video_start_seconds, video_end_seconds)
values ('les-lif-0403', 'mod-lif-04', 'course-lifting', 'higiene-anmat-lifting', 3, 'Higiene, espacio de trabajo y ANMAT', 'Bioseguridad del espacio y verificación de productos aprobados.', 'pdf', '[{"kind":"list","title":"Higiene y espacio de trabajo","items":["Desinfectar siempre manos y materiales.","Los materiales descartables no se pueden volver a usar.","Zona de trabajo limpia y desinfectada.","Procurar el uso de barbijo.","Camilla con colchoneta o silla cómoda.","Ambiente con buen aroma."]},{"kind":"callout","tone":"warning","title":"Importante — ANMAT","text":"Al comprar cualquier producto debemos verificar que esté aprobado por la ANMAT para garantizar productos eficaces, seguros y de calidad."}]'::jsonb, '["Mantener un espacio seguro","Verificar aprobación ANMAT"]'::jsonb, '["Desinfección","Descartables","ANMAT"]'::jsonb, null, null)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, content = excluded.content, objectives = excluded.objectives, highlights = excluded.highlights, position = excluded.position;

commit;
